#!/bin/bash
#
# Copyright (c) 2019 University of Utah
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR(S) DISCLAIM ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL AUTHORS BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# Export DPDK bindings to the current shell.
export LD_LIBRARY_PATH=$(pwd)/net/target/native

cd splinter

# Check for a TOML file with client related configuration.
if [[ ! -f client.toml ]]; then
    echo "Missing client.toml file (in splinter directory)."
    exit -1
fi

# Get the "use_invoke" field from the client configuration. The output file
# will be marked with the value of this field, allowing to distinguish between
# experiments run with an invoke based PUSHBACK, and experiments run with a native
# operation based PUSHBACK.
invoke=$(cat client.toml | grep "use_invoke" | awk '{ print $NF }')

# The number of tenants requests are being generated for.
tenants=$(cat client.toml | grep "num_tenants" | awk '{ print $NF }')

# The skew with which tenants are chosen by the client.
tenant_skew=$(cat client.toml | grep "tenant_skew" | awk '{ print $NF }')

# The number of server cores being stressed by PUSHBACK.
cores=$(cat client.toml | grep "server_udp_ports" | awk '{ print $NF }')

# The request rate configured in the client.toml file.
rate=$(cat client.toml | grep "req_rate" | awk '{ print $NF }')

# SLO target values to test (unit: Cycles).
slo_values=(240000 480000 720000)

# order-order2 combinations to test.
order_values=(240 24 6)
order2_values=(2400 240 60)

# Header for the output file. Required in order to plot the results.
echo "Offered Slo Order Order2 50 99 Tenants TSkew Cores Thrpt" > ../pushback_kayak_invoke_"$invoke".data

# Run PUSHBACK-KAYAK for each combination of slo and (order, order2).
for slo in "${slo_values[@]}"
do
    # Configure the client TOML file with the slo value.
    sed -i "s/^slo = [0-9]*/slo = $slo/" client.toml

    for idx in 0 1 2
    do
        ord="${order_values[$idx]}"
        ord2="${order2_values[$idx]}"

        # Configure the client TOML file with the order and order2 values.
        # Anchor to line start to avoid matching "order2" when replacing "order".
        sed -i "s/^order2 = [0-9]*/order2 = $ord2/" client.toml
        sed -i "s/^order = [0-9]*/order = $ord/" client.toml

        echo "rate=$rate, invoke=$invoke, tenants=$tenants, tenant_skew=$tenant_skew, cores=$cores, slo=$slo, order=$ord, order2=$ord2"

        # Run PUSHBACK-KAYAK, and write out the output to a file.
        rm -f ../samples.temp
        RUST_LOG=debug ./target/release/pushback-kayak >> ../samples.temp 2>&1

        # Calculate the total measured server throughput.
        thrpt=$(cat ../samples.temp | grep "PUSHBACK Throughput" | \
            awk 'BEGIN { sum = 0 } { sum += $3 } END { print sum }')

        # Print the panic!() message on the console to avoid any error.
        cat ../samples.temp | grep "panicked"

        # Print final numbers to a file.
        cat ../samples.temp | grep ">>>" | \
            awk "{ print $rate, $slo, $ord, $ord2, \$2, \$3, $tenants, $tenant_skew, $cores, $thrpt }" >> \
            ../pushback_kayak_invoke_"$invoke".data

        # Cleanup temp file.
        rm ../samples.temp

    done
done

exit 0
